description: Bruno Wollmann's blog about Networking
opengraph: true
twitter_cards: true
readmore: false
authorbox: false
pager: true
post_meta: [date, categories]
mainSections: [posts]

logo:
  image: /Logo.jpg
  title: Bruno Wollmann on Networking
  subtitle: Just another site about Networking

sidebar:
  home: right
  list: right
  single:
  widgets: [recent, social, categories, taglist]

widgets:
  recent_num: 5
  tags_counter: false
  social:
    twitter: wollmannbruno
    linkedin: wollmannbruno
    github: wollmannbruno

style:
  vars:
    highlightColor: #0288d1
